//! ラベル付き API キーの平文ファイル。
//!
//! 脅威モデルはプライベート網であり、鍵ファイルはサーバ上にある。ハッシュ化が
//! 守るものは乏しい一方、新しいクライアントを設定するときに既存の鍵を読み直せる
//! 利便性が効くため、平文で保存する。
//!
//! 書き込みは常に全上書きで、先頭の書式説明コメントを毎回再生成する。注釈用途は
//! `label` が担うので、ユーザーの独自コメントは保持しない。

use std::collections::HashSet;
use std::path::{Path, PathBuf};

use base64::Engine as _;
use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

use crate::error::{Error, Result};

/// 保存時に毎回書き出す書式説明。
const HEADER: &str = "\
# sapphire API keys.
#
# To add a key by hand, append a `[[key]]` table with just a `token`; the
# remaining fields are filled in and written back the next time the server
# loads this file. Generating and revoking keys from a command line is a job
# for the application server that embeds sapphire-framework — the framework
# itself ships no subcommands.
#
# token       required. Any string the client will send as `Bearer <token>`.
#             `<prefix>_<random>` when generated by an application server.
# id          optional. A UUID. Filled in on load when blank. Ties a key to a
#             user or device, so it survives a label change. Ids must be
#             unique within this file.
# label       optional. A note for you, like an authorized_keys comment.
#             Nothing in the system reads it.
# created_at  optional. RFC 3339. Filled in on load when blank.
# expires_at  optional. RFC 3339. Absent means the key never expires.
#
# This file is rewritten in full on every change; comments you add are lost.
";

/// 一件の API キー。
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct KeyEntry {
    pub token: String,
    pub id: Uuid,
    pub label: Option<String>,
    pub created_at: DateTime<Utc>,
    pub expires_at: Option<DateTime<Utc>>,
}

impl KeyEntry {
    /// `expires_at` を過ぎているか。
    pub fn is_expired(&self, now: DateTime<Utc>) -> bool {
        self.expires_at.is_some_and(|e| e <= now)
    }
}

/// ファイル上の表現。手書きを許すため `id` / `created_at` は省略可。
#[derive(Debug, Serialize, Deserialize)]
struct RawKey {
    token: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    label: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    created_at: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    expires_at: Option<DateTime<Utc>>,
}

#[derive(Debug, Default, Serialize, Deserialize)]
struct RawFile {
    #[serde(default)]
    key: Vec<RawKey>,
}

/// 鍵ファイルとその中身。
pub struct KeyStore {
    path: PathBuf,
    entries: Vec<KeyEntry>,
}

impl KeyStore {
    /// 読み込み、欠けた `id` / `created_at` を補完する。補完があれば書き戻す。
    /// ファイルが無い場合は空のストアを返す（作成はしない）。
    pub fn load(path: &Path) -> Result<Self> {
        let raw: RawFile = match std::fs::read_to_string(path) {
            Ok(text) => toml::from_str(&text)
                .map_err(|e| Error::KeyFile(format!("{}: {e}", path.display())))?,
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => RawFile::default(),
            Err(e) => return Err(Error::Io(e)),
        };

        // 重複したまま読み込むと revoke がどちらの鍵か決められない。UUID を手で
        // 書くことはまず無いが、エントリごとコピーして複製する事故はある。
        let mut seen: HashSet<Uuid> = HashSet::new();
        for k in &raw.key {
            if let Some(id) = k.id
                && !seen.insert(id)
            {
                return Err(Error::KeyFile(format!(
                    "{}: two keys share the id {id}",
                    path.display()
                )));
            }
        }

        let mut filled = false;
        let now = Utc::now();
        let mut entries: Vec<KeyEntry> = Vec::with_capacity(raw.key.len());
        for k in raw.key {
            if k.id.is_none() || k.created_at.is_none() {
                filled = true;
            }
            entries.push(KeyEntry {
                token: k.token,
                id: k.id.unwrap_or_else(Uuid::new_v4),
                label: k.label,
                created_at: k.created_at.unwrap_or(now),
                expires_at: k.expires_at,
            });
        }

        let store = Self {
            path: path.to_path_buf(),
            entries,
        };
        if filled {
            store.save()?;
        }
        Ok(store)
    }

    pub fn entries(&self) -> &[KeyEntry] {
        &self.entries
    }

    /// 新しい鍵を生成して追記・保存する。
    ///
    /// `id` を渡すとその値を使う。アプリが device 行を先に書いてから鍵を作れる
    /// ようにするため。既に使われている id を渡した場合は**空きを探さずに**
    /// 失敗する — 呼び出し側は特定の id を要求しているので、別の id を黙って
    /// 返すのは要求に応えていない。
    pub fn generate(
        &mut self,
        prefix: &str,
        id: Option<Uuid>,
        label: Option<String>,
        expires_at: Option<DateTime<Utc>>,
    ) -> Result<KeyEntry> {
        let id = match id {
            Some(id) => {
                if self.entries.iter().any(|e| e.id == id) {
                    return Err(Error::KeyFile(format!(
                        "a key with the id {id} already exists"
                    )));
                }
                id
            }
            None => Uuid::new_v4(),
        };

        let mut bytes = [0u8; 32];
        getrandom::getrandom(&mut bytes)
            .map_err(|e| Error::KeyFile(format!("no randomness available: {e}")))?;
        let random = base64::engine::general_purpose::URL_SAFE_NO_PAD.encode(bytes);

        let entry = KeyEntry {
            token: format!("{prefix}_{random}"),
            id,
            label,
            created_at: Utc::now(),
            expires_at,
        };
        let mut candidate = self.entries.clone();
        candidate.push(entry.clone());
        self.save_entries(&candidate)?;
        self.entries = candidate;
        Ok(entry)
    }

    /// `selector` を 1 件のエントリの位置に解決する。
    ///
    /// UUID として読めるなら id、読めないなら label を見る。両者の名前空間は
    /// 重ならないので、grain-id のころに要った「id 一致が label 一致より優先」と
    /// いう規則は要らない。
    fn resolve(&self, selector: &str) -> Result<usize> {
        let matches: Vec<usize> = match selector.parse::<Uuid>() {
            Ok(id) => self
                .entries
                .iter()
                .enumerate()
                .filter(|(_, e)| e.id == id)
                .map(|(i, _)| i)
                .collect(),
            Err(_) => self
                .entries
                .iter()
                .enumerate()
                .filter(|(_, e)| e.label.as_deref() == Some(selector))
                .map(|(i, _)| i)
                .collect(),
        };

        match matches.as_slice() {
            [] => Err(Error::KeyFile(format!("no key matches {selector:?}"))),
            [i] => Ok(*i),
            // id は `load` と `generate` が一意性を保証するので、複数一致は
            // label 側でしか起こらない。
            many => Err(Error::KeyFile(format!(
                "{} keys share the label {selector:?}; pass the id instead",
                many.len()
            ))),
        }
    }

    /// `selector`（`id` またはラベル）に一致する鍵を削除する。ラベルが複数一致
    /// する場合はエラーにして `id` を要求する。
    pub fn revoke(&mut self, selector: &str) -> Result<KeyEntry> {
        let i = self.resolve(selector)?;
        let mut candidate = self.entries.clone();
        let removed = candidate.remove(i);
        self.save_entries(&candidate)?;
        self.entries = candidate;
        Ok(removed)
    }

    /// 提示されたトークンを検証する。期限切れは `None`。
    pub fn authenticate(&self, token: &str) -> Option<&KeyEntry> {
        let now = Utc::now();
        self.entries
            .iter()
            .find(|e| constant_time_eq(e.token.as_bytes(), token.as_bytes()) && !e.is_expired(now))
    }

    /// 有効な（期限切れでない）鍵が 1 件以上あるか。
    pub fn has_usable_key(&self) -> bool {
        let now = Utc::now();
        self.entries.iter().any(|e| !e.is_expired(now))
    }

    /// 現在の `self.entries` をヘッダ付きで全上書きする。
    fn save(&self) -> Result<()> {
        self.save_entries(&self.entries)
    }

    /// `entries` をヘッダ付きで全上書きする。`self.entries` には触れない — 呼び出し側
    /// は保存が成功してから代入すること。こうしておけば、ディスクフル等で保存が
    /// 失敗しても、メモリ上の状態とファイルの中身がずれない。
    ///
    /// 書き込みは **一時ファイル → rename**。このファイルは資格情報の唯一の
    /// 保管場所である上に、`load` がフィールドを補完するたび、つまりごく普通の
    /// 起動のたびに書き直される。その場で truncate すると、途中でクラッシュ
    /// したりディスクが埋まったりした瞬間に全トークンが消え、`serve` は以後
    /// 起動を拒否する。同じ手口を `FsBlobStore::put` が既に使っている。
    fn save_entries(&self, entries: &[KeyEntry]) -> Result<()> {
        let raw = RawFile {
            key: entries
                .iter()
                .map(|e| RawKey {
                    token: e.token.clone(),
                    id: Some(e.id),
                    label: e.label.clone(),
                    created_at: Some(e.created_at),
                    expires_at: e.expires_at,
                })
                .collect(),
        };
        let body = toml::to_string_pretty(&raw)
            .map_err(|e| Error::KeyFile(format!("serializing keys: {e}")))?;
        let parent = self.path.parent().unwrap_or_else(|| Path::new("."));
        std::fs::create_dir_all(parent)?;

        let file_name = self
            .path
            .file_name()
            .ok_or_else(|| Error::KeyFile(format!("{} is not a file path", self.path.display())))?;
        let mut tmp_name = file_name.to_os_string();
        tmp_name.push(".tmp");
        let tmp = parent.join(tmp_name);

        // 一時ファイルは最初から 0600 で作る。0644 で作ってから chmod すると、
        // 生成直後のごく短い間だけ全トークンが world-readable になる。
        {
            use std::io::Write as _;
            let mut file = create_private(&tmp)?;
            file.write_all(HEADER.as_bytes())?;
            file.write_all(b"\n")?;
            file.write_all(body.as_bytes())?;
            file.sync_all()?;
        }
        std::fs::rename(&tmp, &self.path).inspect_err(|_| {
            // rename が失敗しても一時ファイルを残さない。中身は平文の鍵。
            let _ = std::fs::remove_file(&tmp);
        })?;
        Ok(())
    }
}

/// 0600（所有者のみ読み書き）で新規作成/切り詰めて開く。
#[cfg(unix)]
fn create_private(path: &Path) -> std::io::Result<std::fs::File> {
    use std::os::unix::fs::OpenOptionsExt as _;
    std::fs::OpenOptions::new()
        .write(true)
        .create(true)
        .truncate(true)
        .mode(0o600)
        .open(path)
}

#[cfg(not(unix))]
fn create_private(path: &Path) -> std::io::Result<std::fs::File> {
    // Windows には 0600 と等価な一発の API が無い。ACL の絞り込みは行わないので、
    // 置き場所で守る前提であることを呼び出し側に伝える。
    tracing::warn!(
        path = %path.display(),
        "key file permissions are not restricted on this platform; keep it out of shared directories"
    );
    std::fs::File::create(path)
}

/// 秘密の比較は長さ以外の情報を漏らさない形で行う。
fn constant_time_eq(a: &[u8], b: &[u8]) -> bool {
    if a.len() != b.len() {
        return false;
    }
    let mut diff = 0u8;
    for (x, y) in a.iter().zip(b.iter()) {
        diff |= x ^ y;
    }
    diff == 0
}

#[cfg(test)]
mod tests {
    use super::*;
    use chrono::Duration;

    fn path(tmp: &tempfile::TempDir) -> std::path::PathBuf {
        tmp.path().join("keys.toml")
    }

    #[test]
    fn load_fills_in_a_hand_written_entry_and_writes_it_back() {
        let tmp = tempfile::tempdir().unwrap();
        let p = path(&tmp);
        std::fs::write(
            &p,
            "[[key]]\ntoken = \"sjt_hand\"\nlabel = \"typed by hand\"\n",
        )
        .unwrap();

        let store = KeyStore::load(&p).unwrap();

        assert_eq!(store.entries().len(), 1);
        let id = store.entries()[0].id;
        assert_ne!(id, Uuid::nil(), "補完された id は nil であってはならない");
        assert_eq!(
            id.to_string().parse::<Uuid>().unwrap(),
            id,
            "表示形から読み戻せる"
        );
        assert_eq!(store.entries()[0].label.as_deref(), Some("typed by hand"));

        // 補完がファイルへ書き戻されていること
        let reloaded = KeyStore::load(&p).unwrap();
        assert_eq!(reloaded.entries()[0].id, store.entries()[0].id);
        assert_eq!(
            reloaded.entries()[0].created_at,
            store.entries()[0].created_at
        );
    }

    #[test]
    fn load_rejects_two_keys_that_share_an_id() {
        // 手で書くことはまず無いが、エントリごとコピーして複製する事故はある。
        // 重複したまま読むと revoke がどちらの鍵か決められない。
        let tmp = tempfile::tempdir().unwrap();
        let p = path(&tmp);
        std::fs::write(
            &p,
            "[[key]]\ntoken = \"sjt_a\"\nid = \"6f1c4a9e-5d2b-4c8f-9a30-1e7b5c8d2f41\"\n\n\
             [[key]]\ntoken = \"sjt_b\"\nid = \"6f1c4a9e-5d2b-4c8f-9a30-1e7b5c8d2f41\"\n",
        )
        .unwrap();

        let err = match KeyStore::load(&p) {
            Ok(_) => panic!("重複した id を受け入れてはならない"),
            Err(e) => e.to_string(),
        };

        assert!(
            err.contains("6f1c4a9e-5d2b-4c8f-9a30-1e7b5c8d2f41"),
            "どの id が重複したか示す: {err}"
        );
    }

    #[test]
    fn generate_uses_the_given_prefix_and_authenticates() {
        let tmp = tempfile::tempdir().unwrap();
        let mut store = KeyStore::load(&path(&tmp)).unwrap();

        let entry = store
            .generate("sjt", None, Some("laptop".into()), None)
            .unwrap();

        assert!(entry.token.starts_with("sjt_"));
        assert_eq!(entry.token.len(), "sjt_".len() + 43);
        assert_eq!(store.authenticate(&entry.token).unwrap().id, entry.id);
        assert!(store.authenticate("sjt_nope").is_none());
    }

    #[test]
    fn an_expired_key_does_not_authenticate() {
        let tmp = tempfile::tempdir().unwrap();
        let mut store = KeyStore::load(&path(&tmp)).unwrap();
        let past = Utc::now() - Duration::hours(1);

        let entry = store.generate("sjt", None, None, Some(past)).unwrap();

        assert!(store.authenticate(&entry.token).is_none());
        assert_eq!(store.entries().len(), 1, "期限切れでも自動削除はしない");
    }

    #[test]
    fn revoke_accepts_an_id_or_a_label_and_rejects_an_ambiguous_one() {
        let tmp = tempfile::tempdir().unwrap();
        let mut store = KeyStore::load(&path(&tmp)).unwrap();
        let a = store
            .generate("sjt", None, Some("dup".into()), None)
            .unwrap();
        store
            .generate("sjt", None, Some("dup".into()), None)
            .unwrap();
        let solo = store
            .generate("sjt", None, Some("solo".into()), None)
            .unwrap();

        assert!(store.revoke("dup").is_err(), "ラベル重複は id を要求する");
        assert_eq!(store.revoke("solo").unwrap().id, solo.id);
        assert_eq!(store.revoke(&a.id.to_string()).unwrap().id, a.id);
        assert_eq!(store.entries().len(), 1);
    }

    #[test]
    fn a_uuid_selector_matches_an_id_and_never_a_label() {
        // 旧 grain-id では `desktop` のような語も 7 文字の正当な id として読めた
        // ため、「id 一致が label 一致より優先」という規則が要った。UUID では
        // 名前空間が重ならないので、parse できるかどうかだけで行き先が決まる。
        let tmp = tempfile::tempdir().unwrap();
        let mut store = KeyStore::load(&path(&tmp)).unwrap();
        let target = store
            .generate("sjt", None, Some("by id".into()), None)
            .unwrap();
        // 別の鍵の id をそのまま label に持つ鍵。
        let decoy = store
            .generate("sjt", None, Some(target.id.to_string()), None)
            .unwrap();

        let removed = store.revoke(&target.id.to_string()).unwrap();

        assert_eq!(removed.id, target.id, "UUID 文字列は id にしか当たらない");
        assert_eq!(store.entries().len(), 1);
        assert_eq!(store.entries()[0].id, decoy.id);
    }

    #[test]
    fn generate_does_not_mutate_state_when_save_fails() {
        let tmp = tempfile::tempdir().unwrap();
        let mut store = KeyStore::load(&path(&tmp)).unwrap();
        let first = store
            .generate("sjt", None, Some("keeper".into()), None)
            .unwrap();

        // Point the store at a path whose parent cannot be created: `afile`
        // already exists as a regular file, so `create_dir_all` on it fails.
        let blocker = tmp.path().join("afile");
        std::fs::write(&blocker, "not a directory").unwrap();
        store.path = blocker.join("keys.toml");

        let before = store.entries().to_vec();
        assert!(
            store
                .generate("sjt", None, Some("doomed".into()), None)
                .is_err()
        );
        assert_eq!(
            store.entries(),
            before.as_slice(),
            "a failed save must not mutate in-memory state"
        );
        assert_eq!(store.entries().len(), 1);
        assert_eq!(store.entries()[0].id, first.id);
    }

    #[test]
    fn revoke_does_not_mutate_state_when_save_fails() {
        let tmp = tempfile::tempdir().unwrap();
        let mut store = KeyStore::load(&path(&tmp)).unwrap();
        let entry = store
            .generate("sjt", None, Some("keeper".into()), None)
            .unwrap();

        let blocker = tmp.path().join("afile");
        std::fs::write(&blocker, "not a directory").unwrap();
        store.path = blocker.join("keys.toml");

        let before = store.entries().to_vec();
        assert!(store.revoke("keeper").is_err());
        assert_eq!(
            store.entries(),
            before.as_slice(),
            "a failed save must not mutate in-memory state"
        );
        assert_eq!(store.entries().len(), 1);
        assert_eq!(store.entries()[0].id, entry.id);
    }

    #[test]
    fn has_usable_key_ignores_expired_keys() {
        let tmp = tempfile::tempdir().unwrap();
        let mut store = KeyStore::load(&path(&tmp)).unwrap();
        let past = Utc::now() - Duration::hours(1);

        store.generate("sjt", None, None, Some(past)).unwrap();
        assert!(!store.has_usable_key(), "only an expired key exists");

        store.generate("sjt", None, None, None).unwrap();
        assert!(store.has_usable_key(), "a live key now exists");
    }

    #[test]
    fn saving_regenerates_the_header_comment() {
        let tmp = tempfile::tempdir().unwrap();
        let p = path(&tmp);
        let mut store = KeyStore::load(&p).unwrap();
        store.generate("sjt", None, None, None).unwrap();

        let text = std::fs::read_to_string(&p).unwrap();
        assert!(text.starts_with("# "), "先頭に書式説明のヘッダが要る");
        assert!(text.contains("label"));
        assert!(
            !text.contains("grain-id"),
            "id はもう grain-id ではない: {text}"
        );
    }

    #[test]
    fn the_header_only_describes_management_that_exists() {
        let tmp = tempfile::tempdir().unwrap();
        let p = path(&tmp);
        let mut store = KeyStore::load(&p).unwrap();
        store.generate("sjt", None, None, None).unwrap();

        let text = std::fs::read_to_string(&p).unwrap();
        assert!(
            !text.contains("gen-key") && !text.contains("revoke-key"),
            "存在しないサブコマンドを案内してはならない: {text}"
        );
        assert!(
            text.contains("by hand"),
            "手書きで足せることを書いておく: {text}"
        );
    }

    #[test]
    fn a_failed_save_leaves_the_existing_key_file_intact() {
        // 鍵ファイルは資格情報の唯一の保管場所で、`load` が補完を書き戻すたび
        // ——つまりごく普通の起動のたびに——書き直される。その場で truncate して
        // いると、書き込みが途中で失敗した瞬間に全トークンが消える。
        // 一時ファイル経由なら、失敗しても本体は前の内容のまま残る。
        let tmp = tempfile::tempdir().unwrap();
        let p = path(&tmp);
        let mut store = KeyStore::load(&p).unwrap();
        let keeper = store
            .generate("sjt", None, Some("keeper".into()), None)
            .unwrap();
        let before = std::fs::read_to_string(&p).unwrap();

        // 一時ファイルの置き場所をディレクトリで塞ぐ → 一時ファイルを作れない。
        // 本体を直接 truncate する実装なら、ここは素通りして上書きしてしまう。
        std::fs::create_dir(tmp.path().join("keys.toml.tmp")).unwrap();

        assert!(
            store
                .generate("sjt", None, Some("doomed".into()), None)
                .is_err(),
            "一時ファイルを作れないなら保存は失敗しなければならない"
        );
        assert_eq!(
            std::fs::read_to_string(&p).unwrap(),
            before,
            "失敗した保存が本体を書き換えてはならない"
        );
        let reloaded = KeyStore::load(&p).unwrap();
        assert_eq!(reloaded.entries().len(), 1);
        assert_eq!(reloaded.entries()[0].id, keeper.id);
    }

    #[test]
    fn a_successful_save_leaves_no_temp_file_behind() {
        let tmp = tempfile::tempdir().unwrap();
        let p = path(&tmp);
        let mut store = KeyStore::load(&p).unwrap();
        store.generate("sjt", None, None, None).unwrap();

        assert!(
            !tmp.path().join("keys.toml.tmp").exists(),
            "平文の鍵を含む一時ファイルを残してはならない"
        );
    }

    #[test]
    fn generate_uses_a_supplied_id() {
        // アプリは device 行を先に書いてから鍵を作る。id を渡せなければ
        // 「鍵を作る → 返った id を device 行に書く」順しか取れず、途中で失敗
        // したときに動くオーファン鍵が残る。
        let tmp = tempfile::tempdir().unwrap();
        let mut store = KeyStore::load(&path(&tmp)).unwrap();
        let want: Uuid = "6f1c4a9e-5d2b-4c8f-9a30-1e7b5c8d2f41".parse().unwrap();

        let entry = store
            .generate("sjt", Some(want), Some("iPhone".into()), None)
            .unwrap();

        assert_eq!(entry.id, want);
        let reloaded = KeyStore::load(&path(&tmp)).unwrap();
        assert_eq!(reloaded.entries()[0].id, want, "ファイルにも入っている");
    }

    #[test]
    fn generate_rejects_an_id_that_is_already_taken() {
        // 呼び出し側は特定の id を要求している。空きを探して別の id を黙って
        // 返すのは要求に応えていない。
        let tmp = tempfile::tempdir().unwrap();
        let mut store = KeyStore::load(&path(&tmp)).unwrap();
        let first = store
            .generate("sjt", None, Some("keeper".into()), None)
            .unwrap();

        let err = match store.generate("sjt", Some(first.id), None, None) {
            Ok(e) => panic!("使われている id を受け入れてはならない: {}", e.id),
            Err(e) => e.to_string(),
        };

        assert!(err.contains(&first.id.to_string()), "どの id か示す: {err}");
        assert_eq!(
            store.entries().len(),
            1,
            "失敗した生成が鍵を増やしてはならない"
        );
    }

    #[test]
    fn generate_without_an_id_mints_a_fresh_one() {
        let tmp = tempfile::tempdir().unwrap();
        let mut store = KeyStore::load(&path(&tmp)).unwrap();

        let a = store.generate("sjt", None, None, None).unwrap();
        let b = store.generate("sjt", None, None, None).unwrap();

        assert_ne!(a.id, b.id);
        assert_ne!(a.id, Uuid::nil());
    }

    #[cfg(unix)]
    #[test]
    fn the_key_file_is_never_world_readable_even_for_an_instant() {
        use std::os::unix::fs::PermissionsExt as _;
        let tmp = tempfile::tempdir().unwrap();
        let p = path(&tmp);
        let mut store = KeyStore::load(&p).unwrap();
        store.generate("sjt", None, None, None).unwrap();

        let mode = std::fs::metadata(&p).unwrap().permissions().mode() & 0o777;
        assert_eq!(mode, 0o600, "0644 で作ってから chmod する窓を残さない");
    }
}
